"""empty message

Revision ID: 666427991dc4
Revises: 0161ee9f7fe0
Create Date: 2024-01-29 21:07:42.579992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '666427991dc4'
down_revision = '0161ee9f7fe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=300),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
